#ifndef MICROPY_INCLUDED_ESP32_MODTHYMIO_H
#define MICROPY_INCLUDED_ESP32_MODTHYMIO_H

#define THYMIO_API_MAJOR_VERSION 0
#define THYMIO_API_MINOR_VERSION 1

#endif // MICROPY_INCLUDED_ESP32_MODTHYMIO_H
